Fix #28
lzfse/lzfse pull request #36
Opened 2017-03-04 13:27 UTC by a7vinx

Handle the possible NULL pointer argument by adding a wrapper to lzfse_encode_buffer/lzfse_decode_buffer. Directly insert malloc/free into origin function will make it ugly because of complicated logic with multiple exits in lzfse_encode_buffer. Tested By libfuzzer.

2017-03-04 19:01 UTC, ebainville requested changes
Hi, thanks for your pull request. A few changes are required. -- E

2017-03-04 19:01 UTC, ebainville commented on src/lzfse_decode.c
> +#include <stdio.h>
I'd prefer to not have the library printing anything. No stdio.h and no perror.

2017-03-04 19:01 UTC, ebainville commented on src/lzfse_decode.c
> +size_t lzfse_do_decode_buffer(uint8_t *__restrict dst_buffer, size_t dst_size,
I don't like the 'do_decode'. What about lzfse_decode_buffer_<something>. 'with_scratch', 'no_alloc', or any suggestions? Same for do_encode.

2017-03-04 19:01 UTC, ebainville commented on src/lzfse_decode.c
> +    perror("malloc");
remove, see comment above

2017-03-04 19:01 UTC, ebainville commented on src/lzfse_decode.c
> +    scratch_buffer = malloc(lzfse_encode_scratch_size());
it's assuming scratch size is non 0. It's OK now, but may introduce a latent bug if it changes in the future.

2017-03-04 19:01 UTC, ebainville commented on src/lzfse_encode.c
> +#include <stdio.h>
remove, see previous comments

2017-03-04 19:01 UTC, ebainville commented on src/lzfse_encode.c
> +size_t lzfse_do_encode_buffer(uint8_t *__restrict dst_buffer, size_t dst_size,
rename, see previous comments

2017-03-04 19:01 UTC, ebainville commented on src/lzfse_decode.c
> +    scratch_buffer = malloc(lzfse_encode_scratch_size());
also, it should be **decode**_scratch_size, not encode, which is larger so your tests didn't fail.

2017-03-04 19:01 UTC, ebainville commented on src/lzfse_encode.c
> +    scratch_buffer = malloc(lzfse_encode_scratch_size());
see previous remark

2017-03-05 01:28 UTC, a7vinx commented on src/lzfse_decode.c
> +    scratch_buffer = malloc(lzfse_encode_scratch_size());
So let it allocate at least one Byte? Or what better way?

2017-03-05 01:30 UTC, a7vinx commented on src/lzfse_decode.c
> +    scratch_buffer = malloc(lzfse_encode_scratch_size());
Shame on me. I will correct it:)

2017-03-08 22:48 UTC, ebainville approved these changes

2017-03-08 22:48 UTC, merged

2017-03-08 22:49 UTC, ebainville commented
Thanks for taking care of this. -- E